apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dotnet-pg-microservice
  labels:
    app: dotnet-pg-microservice
spec:
  to:
    kind: Service
    name: dotnet-pg-microservice
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
