apiVersion: v1
kind: Secret
metadata:
  name: dotnet-pg-microservice-db
  labels:
    app: dotnet-pg-microservice
type: Opaque
stringData:
  DB_HOST: "postgresql"
  DB_PORT: "5432"
  DB_NAME: "microservice_db"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "password"
  CONNECTION_STRING: "Host=postgresql;Port=5432;Database=microservice_db;Username=postgres;Password=password"