apiVersion: v1
kind: Service
metadata:
  name: dotnet-pg-microservice
  labels:
    app: dotnet-pg-microservice
spec:
  selector:
    app: dotnet-pg-microservice
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
